# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/acacia.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyPluginDialogBase(object):
    def setupUi(self, MyPluginDialogBase):
        MyPluginDialogBase.setObjectName("MyPluginDialogBase")
        MyPluginDialogBase.setEnabled(True)
        MyPluginDialogBase.resize(851, 709)
        self.button_box = QtWidgets.QDialogButtonBox(MyPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(500, 670, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.groupBox = QtWidgets.QGroupBox(MyPluginDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(20, 260, 401, 301))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 161, 31))
        self.label.setObjectName("label")
        self.pushButton_INP = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_INP.setGeometry(QtCore.QRect(350, 30, 41, 27))
        self.pushButton_INP.setObjectName("pushButton_INP")
        self.lineEdit_val = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_val.setGeometry(QtCore.QRect(140, 110, 181, 27))
        self.lineEdit_val.setFrame(True)
        self.lineEdit_val.setDragEnabled(False)
        self.lineEdit_val.setObjectName("lineEdit_val")
        self.lineEdit_INP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_INP.setGeometry(QtCore.QRect(140, 30, 201, 27))
        self.lineEdit_INP.setObjectName("lineEdit_INP")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_INP_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_INP_2.setGeometry(QtCore.QRect(140, 70, 201, 27))
        self.lineEdit_INP_2.setObjectName("lineEdit_INP_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.label_2.setObjectName("label_2")
        self.helpButton_num = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_num.setGeometry(QtCore.QRect(160, 220, 21, 20))
        self.helpButton_num.setObjectName("helpButton_num")
        self.lineEdit_num = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_num.setGeometry(QtCore.QRect(10, 220, 151, 27))
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 141, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton_val = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_val.setGeometry(QtCore.QRect(350, 110, 41, 27))
        self.pushButton_val.setObjectName("pushButton_val")
        self.helpButton_val = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_val.setGeometry(QtCore.QRect(320, 110, 21, 20))
        self.helpButton_val.setObjectName("helpButton_val")
        self.checkBox_REL = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_REL.setGeometry(QtCore.QRect(210, 220, 92, 23))
        self.checkBox_REL.setObjectName("checkBox_REL")
        self.helpButton_REL = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_REL.setGeometry(QtCore.QRect(300, 220, 21, 20))
        self.helpButton_REL.setObjectName("helpButton_REL")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 150, 111, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_field = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_field.setGeometry(QtCore.QRect(140, 150, 181, 27))
        self.lineEdit_field.setFrame(True)
        self.lineEdit_field.setDragEnabled(False)
        self.lineEdit_field.setObjectName("lineEdit_field")
        self.helpButton_field = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_field.setGeometry(QtCore.QRect(320, 150, 21, 20))
        self.helpButton_field.setObjectName("helpButton_field")
        self.groupBox_2 = QtWidgets.QGroupBox(MyPluginDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 260, 401, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_ATH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ATH.setGeometry(QtCore.QRect(190, 70, 41, 27))
        self.lineEdit_ATH.setObjectName("lineEdit_ATH")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.label_9.setObjectName("label_9")
        self.lineEdit_QTH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_QTH.setGeometry(QtCore.QRect(190, 100, 41, 27))
        self.lineEdit_QTH.setObjectName("lineEdit_QTH")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 181, 31))
        self.label_10.setObjectName("label_10")
        self.lineEdit_ACH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ACH.setGeometry(QtCore.QRect(190, 130, 41, 27))
        self.lineEdit_ACH.setObjectName("lineEdit_ACH")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 130, 121, 31))
        self.label_11.setObjectName("label_11")
        self.lineEdit_QCH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_QCH.setGeometry(QtCore.QRect(190, 160, 41, 27))
        self.lineEdit_QCH.setObjectName("lineEdit_QCH")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 160, 171, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 190, 141, 31))
        self.label_18.setObjectName("label_18")
        self.lineEdit_PCH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_PCH.setGeometry(QtCore.QRect(190, 190, 41, 27))
        self.lineEdit_PCH.setObjectName("lineEdit_PCH")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 161, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_OUT = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_OUT.setGeometry(QtCore.QRect(150, 30, 191, 27))
        self.lineEdit_OUT.setObjectName("lineEdit_OUT")
        self.pushButton_OUT = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_OUT.setGeometry(QtCore.QRect(350, 30, 41, 27))
        self.pushButton_OUT.setObjectName("pushButton_OUT")
        self.helpButton_ach = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_ach.setGeometry(QtCore.QRect(230, 130, 21, 20))
        self.helpButton_ach.setObjectName("helpButton_ach")
        self.helpButton_ath = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_ath.setGeometry(QtCore.QRect(230, 70, 21, 20))
        self.helpButton_ath.setObjectName("helpButton_ath")
        self.helpButton_bth = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_bth.setGeometry(QtCore.QRect(230, 100, 21, 20))
        self.helpButton_bth.setObjectName("helpButton_bth")
        self.helpButton_BCH = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_BCH.setGeometry(QtCore.QRect(230, 160, 21, 20))
        self.helpButton_BCH.setObjectName("helpButton_BCH")
        self.helpButton_pch = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_pch.setGeometry(QtCore.QRect(230, 190, 21, 20))
        self.helpButton_pch.setObjectName("helpButton_pch")
        self.checkBox_area = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_area.setGeometry(QtCore.QRect(10, 220, 61, 23))
        self.checkBox_area.setObjectName("checkBox_area")
        self.checkBox_perim = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_perim.setGeometry(QtCore.QRect(10, 240, 61, 23))
        self.checkBox_perim.setObjectName("checkBox_perim")
        self.checkBox_AGB_mean = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AGB_mean.setGeometry(QtCore.QRect(10, 260, 101, 23))
        self.checkBox_AGB_mean.setObjectName("checkBox_AGB_mean")
        self.checkBox_AGB_iqr = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AGB_iqr.setGeometry(QtCore.QRect(10, 280, 101, 23))
        self.checkBox_AGB_iqr.setObjectName("checkBox_AGB_iqr")
        self.checkBox_convexity = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_convexity.setGeometry(QtCore.QRect(120, 220, 91, 23))
        self.checkBox_convexity.setObjectName("checkBox_convexity")
        self.checkBox_rect = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_rect.setGeometry(QtCore.QRect(120, 240, 91, 23))
        self.checkBox_rect.setObjectName("checkBox_rect")
        self.checkBox_AGBCh_mean = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AGBCh_mean.setGeometry(QtCore.QRect(120, 260, 121, 23))
        self.checkBox_AGBCh_mean.setObjectName("checkBox_AGBCh_mean")
        self.checkBox_AGBCh_iqr = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AGBCh_iqr.setGeometry(QtCore.QRect(120, 280, 101, 23))
        self.checkBox_AGBCh_iqr.setObjectName("checkBox_AGBCh_iqr")
        self.checkBox_AGBR_iqr = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AGBR_iqr.setGeometry(QtCore.QRect(250, 280, 101, 23))
        self.checkBox_AGBR_iqr.setObjectName("checkBox_AGBR_iqr")
        self.checkBox_AGBR_mean = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_AGBR_mean.setGeometry(QtCore.QRect(250, 260, 121, 23))
        self.checkBox_AGBR_mean.setObjectName("checkBox_AGBR_mean")
        self.progressBar_PRC = QtWidgets.QProgressBar(MyPluginDialogBase)
        self.progressBar_PRC.setGeometry(QtCore.QRect(140, 670, 331, 23))
        self.progressBar_PRC.setProperty("value", 0)
        self.progressBar_PRC.setObjectName("progressBar_PRC")
        self.label_12 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_12.setGeometry(QtCore.QRect(20, 670, 121, 17))
        self.label_12.setObjectName("label_12")
        self.label_19 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_21.setGeometry(QtCore.QRect(470, 10, 321, 241))
        self.label_21.setObjectName("label_21")
        self.groupBox_3 = QtWidgets.QGroupBox(MyPluginDialogBase)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 570, 811, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Help_label = QtWidgets.QLabel(self.groupBox_3)
        self.Help_label.setGeometry(QtCore.QRect(10, 30, 791, 51))
        self.Help_label.setObjectName("Help_label")
        self.ManualButton = QtWidgets.QPushButton(MyPluginDialogBase)
        self.ManualButton.setGeometry(QtCore.QRect(480, 670, 161, 25))
        self.ManualButton.setObjectName("ManualButton")
        self.label_23 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_23.setGeometry(QtCore.QRect(20, 76, 381, 171))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_24.setGeometry(QtCore.QRect(620, 40, 91, 51))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_25.setGeometry(QtCore.QRect(789, 10, 41, 241))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_26.setGeometry(QtCore.QRect(440, 10, 41, 241))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_28.setGeometry(QtCore.QRect(720, 40, 51, 51))
        self.label_28.setObjectName("label_28")

        self.retranslateUi(MyPluginDialogBase)
        self.button_box.accepted.connect(MyPluginDialogBase.accept)
        self.button_box.rejected.connect(MyPluginDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(MyPluginDialogBase)

    def retranslateUi(self, MyPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MyPluginDialogBase.setWindowTitle(_translate("MyPluginDialogBase", "Biota Graphical Interface"))
        self.groupBox.setTitle(_translate("MyPluginDialogBase", "Primary inputs"))
        self.label.setText(_translate("MyPluginDialogBase", "Input initial data"))
        self.pushButton_INP.setText(_translate("MyPluginDialogBase", "..."))
        self.label_5.setText(_translate("MyPluginDialogBase", "Validation data"))
        self.label_2.setText(_translate("MyPluginDialogBase", "Input data change"))
        self.helpButton_num.setText(_translate("MyPluginDialogBase", "?"))
        self.label_4.setText(_translate("MyPluginDialogBase", "Number of elements"))
        self.pushButton_val.setText(_translate("MyPluginDialogBase", "..."))
        self.helpButton_val.setText(_translate("MyPluginDialogBase", "?"))
        self.checkBox_REL.setText(_translate("MyPluginDialogBase", "Relative?"))
        self.helpButton_REL.setText(_translate("MyPluginDialogBase", "?"))
        self.label_7.setText(_translate("MyPluginDialogBase", "Field name"))
        self.helpButton_field.setText(_translate("MyPluginDialogBase", "?"))
        self.groupBox_2.setTitle(_translate("MyPluginDialogBase", "Secondary inputs"))
        self.lineEdit_ATH.setText(_translate("MyPluginDialogBase", "1"))
        self.label_9.setText(_translate("MyPluginDialogBase", "Area threshold (px)"))
        self.lineEdit_QTH.setText(_translate("MyPluginDialogBase", "10"))
        self.label_10.setText(_translate("MyPluginDialogBase", "Quantity threshold (x/px)"))
        self.lineEdit_ACH.setText(_translate("MyPluginDialogBase", "1"))
        self.label_11.setText(_translate("MyPluginDialogBase", "Area change (px)"))
        self.lineEdit_QCH.setText(_translate("MyPluginDialogBase", "5"))
        self.label_17.setText(_translate("MyPluginDialogBase", "Quantity change (x/px)"))
        self.label_18.setText(_translate("MyPluginDialogBase", "Percentage change"))
        self.lineEdit_PCH.setText(_translate("MyPluginDialogBase", "10"))
        self.label_6.setText(_translate("MyPluginDialogBase", "Output data folder"))
        self.pushButton_OUT.setText(_translate("MyPluginDialogBase", "..."))
        self.helpButton_ach.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_ath.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_bth.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_BCH.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_pch.setText(_translate("MyPluginDialogBase", "?"))
        self.checkBox_area.setText(_translate("MyPluginDialogBase", "area"))
        self.checkBox_perim.setText(_translate("MyPluginDialogBase", "perim"))
        self.checkBox_AGB_mean.setText(_translate("MyPluginDialogBase", "AGB_mean"))
        self.checkBox_AGB_iqr.setText(_translate("MyPluginDialogBase", "AGB_iqr"))
        self.checkBox_convexity.setText(_translate("MyPluginDialogBase", "convexity"))
        self.checkBox_rect.setText(_translate("MyPluginDialogBase", "rect"))
        self.checkBox_AGBCh_mean.setText(_translate("MyPluginDialogBase", "AGBCh_mean"))
        self.checkBox_AGBCh_iqr.setText(_translate("MyPluginDialogBase", "AGBCh_iqr"))
        self.checkBox_AGBR_iqr.setText(_translate("MyPluginDialogBase", "AGBR_iqr"))
        self.checkBox_AGBR_mean.setText(_translate("MyPluginDialogBase", "AGBR_mean"))
        self.label_12.setText(_translate("MyPluginDialogBase", "Processing data"))
        self.label_19.setText(_translate("MyPluginDialogBase", "THIS IS ACACIA"))
        self.label_21.setText(_translate("MyPluginDialogBase", "SMFM logo"))
        self.groupBox_3.setTitle(_translate("MyPluginDialogBase", "Help"))
        self.Help_label.setText(_translate("MyPluginDialogBase", "Click on the help buttons to get parameter definitions"))
        self.ManualButton.setText(_translate("MyPluginDialogBase", "Acacia manual"))
        self.label_23.setText(_translate("MyPluginDialogBase", "Input <data at t1> and <change between t1 and t2> to generate a shapefile of subsampled and clustered change events"))
        self.label_24.setText(_translate("MyPluginDialogBase", "LTS LOGO"))
        self.label_25.setText(_translate("MyPluginDialogBase", "white"))
        self.label_26.setText(_translate("MyPluginDialogBase", "white"))
        self.label_28.setText(_translate("MyPluginDialogBase", "uOe LOGO"))


